export const PLANS = [
  {
    subscription: "Basic",
    image: "/static/circle-icons/full-color/png/128px/bikewheel.png",
    price: 0,
    caption: "forever",
    lists: [
      { text: "Your business displayed on bikebook", isAvailable: true },
      { text: "Google reviews import", isAvailable: true },
      { text: "Receive messages", isAvailable: true },
      { text: "Everything in basic", isAvailable: false },
      { text: "Bookings through bikebook", isAvailable: false },
      { text: "Job management system", isAvailable: false },
      { text: "Personal site widget", isAvailable: false },
      // { text: "and more", isAvailable: true },
    ],
    labelAction: "current plan",
  },
  {
    subscription: "Starter",
    price: 4.99,
    caption: "+ £1 per booking through bikebook *",
    lists: [
      { text: "3 prototypes", isAvailable: true },
      { text: "3 boards", isAvailable: true },
      { text: "Up to 5 team members", isAvailable: true },
      { text: "Advanced security", isAvailable: false },
      { text: "Permissions & workflows", isAvailable: false },
    ],
    labelAction: "choose starter",
  },
  {
    subscription: "Premium",
    image: "/static/circle-icons/full-color/png/128px/bike.png",
    price: 9.99,
    caption: "+ £1 per booking through bikebook *",
    lists: [
      { text: "Your business displayed on bikebook", isAvailable: true },
      { text: "Google reviews import", isAvailable: true },
      { text: "Receive messages", isAvailable: true },
      { text: "Everything in basic", isAvailable: true },
      { text: "Bookings through bikebook", isAvailable: true },
      { text: "Job management system", isAvailable: true },
      { text: "Personal site widget", isAvailable: true },
      // { text: "and more", isAvailable: true },
    ],
    labelAction: "Choose premium",
    freeTrialLabelAction: "Try 14 days free",
  },
];
