export const SearchOptions = {
    defaultValues: {
        radius: 30,
        postcode: null,
        keywords: [],
        bikeServiceTypes: [0],
        orderByType: "Distance",
    },
    bikeServiceTypes: [
        "BikeService_Gold",
        "BikeService_Silver",
        "BikeService_Bronze",
        "Assessment"
    ],
    services: [
        { name: "Bike Services (Required as results are compared by this)", type: "category" },
        { name: "Any Service", type: "service", serviceCategory: "BikeService", serviceType: "", serviceId: 0 },
        { name: "Premium Service (Gold)", type: "service", serviceCategory: "BikeService", serviceType: "BikeService_Gold", serviceId: 1 },
        { name: "Standard Service (Silver)", type: "service", serviceCategory: "BikeService", serviceType: "BikeService_Silver", serviceId: 2 },
        { name: "Basic Service (Bronze)", type: "service", serviceCategory: "BikeService", serviceType: "BikeService_Bronze", serviceId: 3 },
        { name: "Assessment", type: "service", serviceCategory: "BikeService", serviceType: "Assessment", serviceId: 4 },
        { name: "EBike Services", type: "category" },
        { name: "Premium Electric Service", type: "service", serviceCategory: "ElectricBikeService", serviceType: "ElectricBike_Gold", serviceId: 5 },
        { name: "Standard Electric Service", type: "service", serviceCategory: "ElectricBikeService", serviceType: "ElectricBike_Silver", serviceId: 6 },
        { name: "Basic Electric Service", type: "service", serviceCategory: "ElectricBikeService", serviceType: "ElectricBike_Bronze", serviceId: 7 },
        { name: "Fittings", type: "category" },
        { name: "Standard Fittings", type: "service", serviceCategory: "Fitting", serviceType: "Fittings_Standard", serviceId: 8 },
        { name: "Extras", type: "category" },

        { name: "All Nuts & Bolts Checked for Tightness", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 9 },
        { name: "Battery Capacity Test", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 10 },
        { name: "Bicycle Build - Child", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 11 },
        { name: "Bicycle Build – Adult", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 12 },
        { name: "Bicycle Damage Report for Insurance Companies", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 13 },
        { name: "Bottom Bracket Fit", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 14 },
        { name: "Brakes Adjusted & Tested", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 15 },
        { name: "Cassette Replacement & Fit", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 16 },
        { name: "Chain Replacement & Fit", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 17 },
        { name: "Complete Strip Down & Rebuild", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 18 },
        { name: "Derailleur Hanger Straightened", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 19 },
        { name: "Drivetrain Service - Items Cleaned, Inspected, Adjusted and Checked", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 20 },
        { name: "External Brake or Gear Cable Fit", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 21 },
        { name: "Fit Handlebar Tape", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 22 },
        { name: "Fit Tubeless Tyre", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 23 },
        { name: "Fit Tubular Tyre", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 24 },
        { name: "Frame Threads Reamed & Faced", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 25 },
        { name: "Gears Adjusted & Tested", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 26 },
        { name: "Headset & Crank Bottom Bracket Adjusted", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 27 },
        { name: "Headset Fit", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 28 },
        { name: "Hubs Adjusted for Play", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 29 },
        { name: "Hydraulic Brake Bleed", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 30 },
        { name: "Internal Brake or Gear Cable Fit", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 31 },
        { name: "Puncture Repair Excluding Inner Tub", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 32 },
        { name: "Puncture Repair Including Inner Tube", type: "service", serviceCategory: "Extra", serviceType: "Extras_PunctureRepair", serviceId: 33 },
        { name: "Rear Mech Hanger Replacement", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 34 },
        { name: "Replace Disc Brake Pads", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 35 },
        { name: "Replace Rim Brake Pad", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 36 },
        { name: "Service - Suspension(Forks)", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 37 },
        { name: "Service – Suspension(Rear)", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 38 },
        { name: "Service Headset", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 39 },
        { name: "Service Hub - Single", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 40 },
        { name: "Software Update & Diagnostic Report", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 41 },
        { name: "Spoke Tensions Balanced & Wheels Re - trued for Alignment", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 42 },
        { name: "Tyres Inflated to Correct Pressures & Inspected for Wear", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 43 },
        { name: "Wheel Build - Pair", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 44 },
        { name: "Wheel Build - Single", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 45 },
        { name: "Wheel True With Spoke", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 46 },
        { name: "Wheels Trued for Correct Alignment", type: "service", serviceCategory: "Extra", serviceType: "Extra", serviceId: 47 },
    ]
}