//const defaultTitle = "Bikebook | Bicycle servicing made easy";
//const defaultDescription = "BikeBook is here to ease the pain of finding a bike service. Compare local bike servicers in your area and find your perfect service in minutesy";

import { result } from "../views/Blog/data/index";
const defaultTitle = "Bikebook | Find local bicycle mechanics online";
const defaultDescription =
  "Bikebook is the easiest, fastest and most transparent way to have your bike serviced. We allow for an instant comparison of services, reviews and prices from mechanics in your area. ";
const defaultImage = "https://bikebook-prod.s3.eu-west-2.amazonaws.com/SiteImages/Logos/Profile_pic.png";

export const RouteDefinitions = [
  {
    path: "/",
    exact: true,
    component: "HomeView",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/signup-business",
    exact: false,
    component: "SignupBusiness",
    layout: "MainLayout",
    defaultTitle: "Bikebook | Join the directory",
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/oauth-callback/:code?/:error?",
    exact: false,
    component: "OAuthCallback",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/about",
    exact: false,
    component: "AboutUs",
    layout: "MainLayout",
    defaultTitle: "Bikebook | About us",
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/home",
    exact: false,
    component: "HomeView",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/business-registration/:pageId?",
    exact: false,
    component: "BusinessRegistration",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "private",
    image: defaultImage,
  },
  {
    path: "/not-found",
    exact: false,
    component: "NotFoundView",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/blog",
    exact: false,
    component: "BlogSearchView",
    layout: "MainLayout",
    defaultTitle: "Bikebook | Blogs",
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/article/:articleId?",
    exact: false,
    component: "BlogArticle",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    data: result,
    image: defaultImage,
  },
  {
    path: "/account/:pageId?",
    exact: false,
    component: "AccountView",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "private",
    image: defaultImage,
  },
  {
    path: "/search-results/:v?/:pn?/:ps?",
    exact: false,
    component: "SearchResults",
    layout: "MainLayout",
    defaultTitle: "Bikebook | Search Results",
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/contact",
    exact: false,
    component: "ContactPage",
    layout: "MainLayout",
    defaultTitle: "Bikebook | Contact us",
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/help",
    exact: false,
    component: "HelpCenterArticle",
    layout: "MainLayout",
    defaultTitle: "Bikebook | FAQ",
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/privacy",
    exact: false,
    component: "CompanyPrivacy",
    layout: "MainLayout",
    defaultTitle: "Bikebook | Privacy Policy",
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/terms",
    exact: false,
    component: "CompanyTerms",
    layout: "MainLayout",
    defaultTitle: "Bikebook | Terms & Conditions",
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/confirm-email/:userId?/:code?/:newEmail?",
    exact: false,
    component: "ConfirmEmail",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/verify-email/:userId?/:code?/",
    exact: false,
    component: "VerifyEmail",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/unsubscribe/:email?",
    exact: false,
    component: "Unsubscribe",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/reset-password/:userId?/:code?",
    exact: false,
    component: "ResetPassword",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/payment",
    exact: false,
    component: "Payment",
    layout: "LogoOnlyLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/pricing",
    exact: false,
    component: "Pricing",
    layout: "LogoOnlyLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/mechanic/:mechanicUrl?/:businessId?",
    exact: false,
    component: "Booking",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
    layoutAttributes: {
      disableFooter: true,
      minimalise: true,
    },
  },
  {
    path: "/tracking/:trackingId",
    exact: false,
    component: "Tracking",
    layout: "MainLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "standard",
    image: defaultImage,
  },
  {
    path: "/app",
    exact: true,
    layout: "DashboardLayout",
    component: "GeneralApp",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    image: defaultImage,
    type: "private",
    children: [
      { path: "/", component: "Dashboard", premium: true },
      { path: "/dashboard", component: "Dashboard", premium: true },
      { path: "/availability", component: "Availability", premium: true },
      {
        path: "/my-business",
        children: [
          { path: "/", component: "MyBusiness" },
          { path: "/:tab?", component: "MyBusiness" },
          { path: "/services/new", component: "CreateService" },
        ],
      },
      {
        path: "/account",
        children: [{ path: "/:tab?", component: "UserAccount" }],
      },
      { path: "/calendar", component: "Calendar", premium: true },
      { path: "/jobs", component: "Jobs", premium: true },
      {
        path: "/chat",
        children: [
          { path: "/", component: "Chat", premium: true },
          { path: "/new/:customerId?", component: "Chat", premium: true },
          { path: "/:conversationKey", component: "Chat", premium: true },
        ],
      },
      { path: "/collection-&-drop-off", component: "CollectionDropoff", premium: true },
      {
        path: "/customers",
        children: [
          { path: "/", component: "Customers", premium: true },
          { path: "/create", component: "CreateCustomer", premium: true },
          { path: "/edit/:customerId", component: "EditCustomer", premium: true },
        ],
      },
      {
        path: "/settings",
        children: [
          { path: "/", component: "Settings" },
          { path: "/update-url", component: "UpdateUrl", premium: true },
          { path: "/install-your-widget", component: "InstallYourWidget", premium: true },
        ],
      },
    ],
  },
  {
    path: "/admin/dashboard",
    exact: false,
    component: "AdminDashboard",
    layout: "MainLayout",
    subLayout: "AdminLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "admin",
    image: defaultImage,
  },
  {
    path: "/admin/emails",
    exact: false,
    component: "AdminEmails",
    layout: "MainLayout",
    subLayout: "AdminLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "admin",
    image: defaultImage,
  },
  {
    path: "/admin/export",
    exact: false,
    component: "AdminExport",
    layout: "MainLayout",
    subLayout: "AdminLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "admin",
    image: defaultImage,
  },
  {
    path: "/admin/user-management",
    exact: false,
    component: "AdminUserManagement",
    layout: "MainLayout",
    subLayout: "AdminLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "admin",
    image: defaultImage,
  },
  {
    path: "/admin/administration-items",
    exact: false,
    component: "AdminAdministrationItems",
    layout: "MainLayout",
    subLayout: "AdminLayout",
    defaultTitle: defaultTitle,
    defaultDescription: defaultDescription,
    type: "admin",
    image: defaultImage,
  },
];
